### ISSUE TITLE
Tentative To-Do List (MVP)

### ISSUE THREAD

**Issue by grumble-down** [mikechabot/eve-arbitrage#2]
To Do order (placeholder)
### **MVP**
_Initial Information Pull_

- [ ] - OAuth with EvE for access to Character and OAuth restricted Corporation Asset data access.
- [ ] - GET /characters/{character_id/corporationhistory  [use this to pull corporation_id]

_Use corporation_id to find the following_

- [ ] -  GET /corporation/{corporation_id}/assets/  [use corporation_ID to pull item_id, location_id, quantity, type_id as main info]
- [ ] - Sort type_id from GET by category_id from CSV (invGroups). This section may need to be adjusted based off feedback from users. Check issue (LINK HERE) for further CSV flow.

--------

_Market Check_

- [ ] - Organized list of type_id to based on location_id, of all assets in "4-HWWF Hangar" - true location TBD.
- [ ]  - GET /markets/{region_id}/orders [This is for the items only in a specific hanger that would be organized above - region ID for Jita is "10000002" - this potentially could be a drop down menu for other markets, not sure if you want to take that into consideration while creating.]
- [ ] - Leveraging the data returned by orders, will need to calculate against the most recent "issued" BUY "price" values.  May want to potentially have the percentage calculations be a drop down menu with the options of 93% / 95% / 100% / 102% of Jita Buy (JTB) values. Math will look like this for each item within a defined hanger:  

> type_id_value = ("price" * asset_item_quantity) * percent_variable

- [ ] - Continue this process for all items within specific hanger. 

### **TO DISCUSS**

- GET /corporations/{corporation_id}  [this information will be useful later, mainly adding to not have to add it later]
- UI after data is gathered
- Find a way to allow people to copy-paste items / quantity for posting directly to Janice for orders?
- potentially do the above with a check list option + maybe a field to input the number of said item they are looking to order so that they  may create a copy / pasteable group selection for passing into Janice 
- Decide if we use the Janice API to tie to the site, or send people there directly.
